FROM ubuntu:22.04
RUN apt-get update
RUN apt-get install -y make && \
    apt-get install -y jq && \
    apt-get install -y nodejs && \ 
    apt-get install -y npm && \ 
    apt-get install -y chromium-browser && \ 
    apt-get install -y cpio 
